<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://ds.hive5.com/elements" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/cards.wsdl"/>
            <oracle-xsl-mapper:rootElement name="updateCardRequest" namespace="http://ds.hive5.com/elements"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/cards.wsdl"/>
            <oracle-xsl-mapper:rootElement name="updateCardRequest" namespace="http://ds.hive5.com/elements"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JUN 25 09:34:48 CEST 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:updateCardRequest>
         <ns0:cardId>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:cardId"/>
         </ns0:cardId>
         <ns0:title>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:title"/>
         </ns0:title>
         <ns0:description>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:description"/>
         </ns0:description>
         <ns0:startDate>
            <xsl:value-of select="concat (/ns0:updateCardRequest/ns0:startDate[1.0], &quot;-&quot;, format-number (/ns0:updateCardRequest/ns0:startDate[2.0], &quot;00&quot; ), &quot;-&quot;, format-number (/ns0:updateCardRequest/ns0:startDate[3.0], &quot;00&quot; ) )"/>
         </ns0:startDate>
         <ns0:endDate>
            <xsl:value-of select="concat (/ns0:updateCardRequest/ns0:endDate[1.0], &quot;-&quot;, format-number (/ns0:updateCardRequest/ns0:endDate[2.0], &quot;00&quot; ), &quot;-&quot;, format-number (/ns0:updateCardRequest/ns0:endDate[3.0], &quot;00&quot; ) )"/>
         </ns0:endDate>
         <ns0:priority>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:priority"/>
         </ns0:priority>
         <ns0:userId>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:userId"/>
         </ns0:userId>
         <ns0:boardId>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:boardId"/>
         </ns0:boardId>
         <ns0:statusId>
            <xsl:value-of select="/ns0:updateCardRequest/ns0:statusId"/>
         </ns0:statusId>
      </ns0:updateCardRequest>
   </xsl:template>
</xsl:stylesheet>
