<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://ds.hive5.com/elements" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/cards.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createCardResponse" namespace="http://ds.hive5.com/elements"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/cards.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createCardResponse" namespace="http://ds.hive5.com/elements"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON JUN 24 09:22:45 CEST 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:createCardResponse>
         <ns0:card>
            <ns0:id>
               <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:id"/>
            </ns0:id>
            <ns0:title>
               <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:title"/>
            </ns0:title>
            <ns0:description>
               <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:description"/>
            </ns0:description>
            <ns0:startDate>
               <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:startDate"/>
            </ns0:startDate>
            <ns0:endDate>
               <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:endDate"/>
            </ns0:endDate>
            <ns0:priority>
               <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:priority"/>
            </ns0:priority>
            <ns0:user>
               <ns0:id>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:id"/>
               </ns0:id>
               <ns0:firstName>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:firstName"/>
               </ns0:firstName>
               <ns0:lastName>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:lastName"/>
               </ns0:lastName>
               <ns0:username>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:username"/>
               </ns0:username>
               <ns0:email>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:email"/>
               </ns0:email>
               <ns0:password>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:password"/>
               </ns0:password>
               <ns0:role>
                  <ns0:id>
                     <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:role/ns0:id"/>
                  </ns0:id>
                  <ns0:name>
                     <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:user/ns0:role/ns0:name"/>
                  </ns0:name>
               </ns0:role>
            </ns0:user>
            <ns0:board>
               <ns0:id>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:board/ns0:id"/>
               </ns0:id>
               <ns0:name>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:board/ns0:name"/>
               </ns0:name>
            </ns0:board>
            <ns0:status>
               <ns0:id>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:status/ns0:id"/>
               </ns0:id>
               <ns0:name>
                  <xsl:value-of select="/ns0:createCardResponse/ns0:card/ns0:status/ns0:name"/>
               </ns0:name>
            </ns0:status>
         </ns0:card>
      </ns0:createCardResponse>
   </xsl:template>
</xsl:stylesheet>
